version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: pitango-postgres
    restart: always
    environment:
      POSTGRES_DB: pitango
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pitango_postgres_data:/var/lib/postgresql/data

volumes:
  pitango_postgres_data:
